server:
  port: 80
  sources:
    - path: /srv
      config:
        createUserDir: true
        defaultEnabled: true
        defaultUserScope: "/"

auth:
  methods:
    password:
      enabled: true
